### ISSUE TITLE
Improve spectrum viewer

### ISSUE THREAD

**Issue by JB-MS** [pymzml/spectrum_viewer#1]
Any ideas for 

- improvement 
- new functionality
- changes

 are welcome.

Feel free to open a pull request.

**Comment by LipidAnalysis** [comment]
There is something wrong when I want to read an .mzml file:
'loading run...
Traceback (most recent call last):
  File "spectrum_viewer.py", line 32, in <module>
    for x,y in run['TIC'].peaks():
  File "D:\python\lib\site-packages\pymzml\run.py", line 185, in __getitem__
    spectrum = self.info["file_object"][identifier]
  File "D:\python\lib\site-packages\pymzml\file_interface.py", line 100, in __getitem__
    return self.file_handler[identifier]
  File "D:\python\lib\site-packages\pymzml\file_classes\standardMzml.py", line 99, in __getitem__
    raise StopIteration
StopIteration'
Can you tell me what should I do?

**Comment by JB-MS** [comment]
Hi,

if you provide me with the file, which does not work, I can have a look what is going wrong.

Can you load the run directly with [pymzML](https://github.com/pymzml/pymzML)?

Cheers,
Johannes
